### ISSUE TITLE
does not have ToEntryMap 

### ISSUE THREAD

**Issue by jingb** [seborama/fuego#13]
how to convert a slice to map like java 
aStream.collect(Collectors.toMap(Model::getId, Function.identity()))

**Comment by seborama** [comment]
Hi @jingb ,
Golang is not an object oriented language in that sense. Slices are plain native types without object-oriented features.
You need to wrap your slice into an iterator of sorts. 
I haven't looked at this in a long time but a goot place to start would be `fuego.EntrySlice`.

**Comment by seborama** [comment]
I see that I considered implementing `ToEntryMap` a while back but never got round to doing it.
Do you fancy raising a PR? Make sure you write a test first 😉

**Comment by seborama** [comment]
Hi @jingb ,

I've added `Collector.ToEntryMap`.

Bonne chance.
Seb
